services:
  virtuoso:
    build:
      context: .
      args:
        VIRTUOSO_VERSION: "7.2.17"
        VIRTUOSO_SHA256: "45385ea8c1940e41d88d628f9318bbc992081c4cd5c4e18b57277b6df516b15b"
    image: kgconstruct/virtuoso:v7.2.17
    environment:
      DBA_PASSWORD: root
      VIRT_SPARQL_ResultSetMaxRows: "10000000"
    ports:
      - "1111:1111"
      - "8890:8890"
    volumes:
      - ./database:/database
      - ./shared:/usr/share/proj:ro
