services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JENA_VERSION: "6.2.0"
        FUSEKI_SHA512: "ba65f5867d2d4741b2ed9e2af5a0d4fbb447909894ab2a0c6bc4dac8997f4fe339c87b13c48d45d054977769f0f8bf763ea346b1f7792d5cdc458041bd43a132"
    image: kgconstruct/fuseki:v6.2.0
    command: ["--tdb2", "--update", "--loc", "/fuseki/databases/DB", "/ds"]
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases
